#!/bin/sh
# -*- mode: sh -*-

### xterm
# xterm()
# {
#     if [ -z "$XTERM_PATH" ]; then
#         XTERM_PATH="$(which xterm | grep '^/')"
#         [ -z "$XTERM_PATH" ] && return 1
#     fi
#     $XTERM_PATH -lf "$HOME/.log/Xterm.$HOSTNAME.$(date +%Y%m%d%H%M%S).$RANDOM.log"
# }


### emacs

EMACS=`command -v emacs`
[ -z "$EMACS" ] && EMACS=`command -v xemacs`
EMACS=${EMACS:-:}
#e() { emacs -fn -\*-fixed-\*-12-\* "$@" & }
e()
{
    $EMACS "$@" &
}
ee()
{
    for ee__f; do
        e "$ee__f"
    done
}

alias ne='$EMACS -nw'
alias neq='$EMACS -quick -nw'

ESHELL="${ESH_SH_CUR_SHORT}_login_shell"
export ESHELL


### vim

# g reclamed for git !
#g() { gvim "$@" & }


### sublime

sublime()
{
    LANG=${LANG:-en_US.UTF-8} sublime_text "$@"
}


### rubymine

rubymine()
{
    rubymine.sh "$@"
}


### pycharm
pycharm()
{
    pycharm=`command -v pycharm`
    case $pycharm in
        /*) ;;
        *) pycharm= ;;
    esac
    if [ -n "$pycharm" ]; then
        "$pycharm" "$@"
        return $?
    fi

    pycharm=`command -v pycharm.sh`
    if [ -n "$pycharm" ]; then
        "$pycharm" "$@" &
    fi

    echo >&2 'no pycharm distribution found'
    return 1
}


### ls
alias l='ls'
alias ll='ls -l'
alias l1='ls -1tr'
alias la='ls -a'

case $ESH_OS in
    Linux)
        LS_COLORS='no=00:fi=00:di=01;34:ln=01;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.gz=01;31:*.bz2=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.avi=01;35:*.fli=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.flac=01;35:*.mp3=01;34:*.mpc=01;35:*.ogg=01;35:*.wav=01;35:'
        export LS_COLORS
        ;;
    FreeBSD)
        LS_COLORS='no=01;37:fi=01;37:di=01;34:ln=01;36:pi=01;32:so=01;35:do=01;35:bd=01;33:cd=01;33:ex=01;31:mi=00;37:or=00;36:'
        export LS_COLORS

        CLICOLOR="enable"
        export CLICOLOR

        LSCOLORS='cxgxhxhxbxhxhxbabacaca'
        export LSCOLORS
        ;;
esac


### terms
xtermadm() { xterm -name xtermadm "$@" & }
admterm() { xterm -name xtermadm "$@" & }
xtermdos() { xterm -name xtermdos "$@" & }
dosterm() { xterm -name xtermdos "$@" & }
xtermcons() { xterm -name xtermcons "$@" & }
consterm() { xterm -name xtermcons "$@" & }
xtermams() { xterm -name xtermams "$@" & }
amsterm() { xterm -name xtermams "$@" & }
myterm() { xterm -name myxterm "$@" & }
myxterm() { xterm -name myxterm "$@" & }
tterm() { xterm -name tterm "$@" & }


### ssh
# -o CheckHostIP=no
alias fssh='ssh -o StrictHostKeyChecking=no -o ConnectTimeout=10'
alias fscp='scp -o StrictHostKeyChecking=no -o ConnectTimeout=10'


### BackSpace
#alias eraz='stty erase '
#stty erase '^H'
#stty intr '^C'


### ruby
bundle_exec()
{
  bundle exec "$@"
}

Bexec()
{
  bundle_exec "$@"
}

Brake()
{
  bundle_exec rake "$@"
}

Bruby()
{
  bundle_exec ruby "$@"
}

Brails()
{
  bundle_exec rails "$@"
}

Bconsole()
{
  bundle_exec console "$@"
}

Birb()
{
  bundle_exec irb "$@"
}

Brspec()
{
    bundle_exec rspec "$@"
}

Bguard()
{
    bundle_exec guard "$@"
}
