#!/bin/sh
# -*- mode: shell -*-

### LANG
if [ -z "$LANG" ]; then
    LANG=C
    export LANG
fi


### HOSTNAME
HOSTNAME=`uname -n`
HOSTNAME_SHORT="${HOSTNAME%%.*}"; export HOSTNAME_SHORT
HOSTNAME_DOMAIN="${HOSTNAME#$HOSTNAME_SHORT}"; export HOSTNAME_DOMAIN


### HOME
home()
{
    cd "$HOME"
}

home_alt()
{
    [ -z "$HOME_ALT" ] &&
        echo >&2 "no HOME_ALT set, check $HOME/.host/home/$HOSTNAME" &&
        return 1
    cd "$HOME_ALT"
}

HOME_ALT=$(cd "$HOME/.host/home/$HOSTNAME" 2>/dev/null && pwd -P)
export HOME_ALT
