#!/bin/sh
# -*- mode: sh -*-


### python
prompt_python()
{
    prompt_python=
    if [ -n "$VIRTUAL_ENV" ] && [ "$VIRTUAL_ENV" != "default" ]; then
        prompt_python="py:$VIRTUAL_ENV"
    fi
}

prompt_python_printf()
{
    if prompt_python; then
        [ -z "$prompt_python" ] || printf "$1" "$prompt_python"
    fi
}


### ruby
prompt_ruby()
{
    prompt_ruby=

    prompt_rbenv
    prompt_ruby="$prompt_rbenv"
}

prompt_rbenv()
{
    prompt_rbenv=

    if [ -n "$RBENV_VERSION" ]; then
        prompt_rbenv="rbenv:$RBENV_VERSION"
    else
        prompt_rbenv__version="`rbenv local 2>/dev/null`"
        if [ -n "$prompt_rbenv__version" ]; then
            prompt_rbenv="rbenv:$prompt_rbenv__version"
        fi
    fi
}

prompt_ruby_printf()
{
    if prompt_ruby; then
        [ -z "$prompt_ruby" ] || printf "$1" "$prompt_ruby"
    fi
}


### git
prompt_git()
{
    prompt_git=
    if _git_info 2>/dev/null; then
        prompt_git="${_git_info__branch}"
        if $_git_info__is_bare; then
            prompt_git="bare:${prompt_git}"
        else
            if $_git_info__diff_staged ||
               $_git_info__diff ||
               $_git_info__untracked ; then
                prompt_git__staged=-
                prompt_git__diff=-
                prompt_git__untracked=-
                $_git_info__diff_staged && prompt_git__staged=*
                $_git_info__diff && prompt_git__diff=*
                $_git_info__untracked && prompt_git__untracked=u
                prompt_git="${prompt_git}:${prompt_git__staged}${prompt_git__diff}${prompt_git__untracked}"
            fi
        fi
    fi
}

prompt_git_printf()
{
    if prompt_git; then
        [ -z "$prompt_git" ] || printf "$1" "$prompt_git"
    fi
}
