#!/bin/sh
# -*- mode: sh -*-


############################################
# utils
############################################

esh_utils_add()
{
    [ -n "$1" ] && [ -n "$2" ] || return 1

    _path_activate "default.lib"
    for esh_utils_add__h in "$HOME" "$HOME_ALT"; do
        [ -z "$esh_utils_add__h" ] && continue
        [ ! -d "$esh_utils_add__h" ] && continue

        "$1" "${esh_utils_add__h}/$2"
    done
    _path_deactivate
}

############################################

esh_utils_add path_add_pre utils
esh_utils_add path_addin_pre tools
