#!/bin/sh
# -*- mode: shell -*-

if _process_ppid && _process_comm "$_process_ppid"; then
    case "$_process_comm" in
        *[Tt][Ee][Rr][Mm]*) export TMUX= ;;
    esac
fi

if _want_auto_tmux; then
    _ensure_tmux_is_running
fi
